# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end
config.vm.define :servidor do |servidor|
servidor.vm.box = "bento/ubuntu-20.04"
servidor.vm.network :private_network, ip: "192.168.100.3"
servidor.vm.provision "shell", path: "script.sh"
servidor.vm.hostname = "servidor"
end
end